
var _ = function() {
    var exports = new PlugIn.Library(new Version("0.1"));

// Generated by Haxe 4.0.0 (git build development @ a018cbd)
(function ($hx_exports) { "use strict";
$hx_exports["samples"] = $hx_exports["samples"] || {};
var samples_HelloWorld = $hx_exports["samples"]["HelloWorld"] = function() { };
samples_HelloWorld.helloWorld = function(selection) {
	var _g = 0;
	var _g1 = selection.solids;
	while(_g < _g1.length) {
		var solid = _g1[_g];
		++_g;
		solid.text = "hello !";
	}
};
samples_HelloWorld.main = function() {
};
samples_HelloWorld.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);


    return exports;
}();
_;
