
var _ = function() {
    var exports = new PlugIn.Library(new Version("0.1}"));

// Generated by Haxe 4.0.0 (git build development @ a018cbd)
(function ($hx_exports) { "use strict";
$hx_exports["samples"] = $hx_exports["samples"] || {};
var HorizontalTextAlignment = function() { };
var Layout = function() { };
var samples_HelloWorld = $hx_exports["samples"]["HelloWorld"] = function() { };
samples_HelloWorld.helloWorld = function(selection) {
	var canvas = selection.canvas;
	var _g = 0;
	var _g1 = selection.solids;
	while(_g < _g1.length) {
		var solid = _g1[_g];
		++_g;
		solid.text = "Hello";
		var rect = solid.geometry;
		var newRect = rect.offsetBy(rect.width + 20,0);
		var circle = canvas.addShape("Circle",newRect);
		circle.text = "World";
		circle.shadowColor = null;
		circle.fillColor = Color.yellow;
		circle.fillType = FillType.Solid;
		circle.automationAction = ["org.epistem.omnigraffle.helloworld","helloWorld"];
		var line = canvas.connect(solid,circle);
		line.headType = "FilledArrow";
		line.shadowColor = null;
	}
};
samples_HelloWorld.main = function() {
};
samples_HelloWorld.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);


    return exports;
}();
_;
