
var _ = function() {
    var exports = new PlugIn.Library(new Version("0.1}"));

// Generated by Haxe 4.0.0 (git build development @ 3018ab1)
(function ($hx_exports) { "use strict";
$hx_exports["samples"] = $hx_exports["samples"] || {};
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.wrap = function(val) {
	if((val instanceof Error)) {
		return val;
	} else {
		return new js__$Boot_HaxeError(val);
	}
};
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if((o instanceof Array)) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			var e1 = (e instanceof js__$Boot_HaxeError) ? e.val : e;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var HorizontalTextAlignment = function() { };
HorizontalTextAlignment.__name__ = true;
var Layout = function() { };
Layout.__name__ = true;
var samples_HelloWorld = $hx_exports["samples"]["HelloWorld"] = function() { };
samples_HelloWorld.__name__ = true;
samples_HelloWorld.helloWorld = function(selection) {
	var canvas = selection.canvas;
	var plugin = PlugIn.all[0];
	console.log("Plugin - " + plugin.identifier);
	var handler = plugin.handlers[0];
	console.log("Handler - " + Std.string(handler));
	var _g = 0;
	var _g1 = selection.solids;
	while(_g < _g1.length) {
		var solid = _g1[_g];
		++_g;
		solid.text = "Hello";
		var rect = solid.geometry;
		var newRect = rect.offsetBy(rect.width + 20,0);
		var circle = canvas.addShape("Circle",newRect);
		circle.text = "World";
		circle.shadowColor = null;
		circle.fillColor = app.optionKeyDown ? Color.orange : Color.yellow;
		circle.fillType = FillType.Solid;
		circle.automationAction = ["org.epistem.omnigraffle.helloworld","helloWorld"];
		var line = canvas.connect(solid,circle);
		line.headType = "FilledArrow";
		line.shadowColor = null;
	}
};
samples_HelloWorld.main = function() {
};
String.__name__ = true;
Array.__name__ = true;
Object.defineProperty(js__$Boot_HaxeError.prototype,"message",{ get : function() {
	return String(this.val);
}});
samples_HelloWorld.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);


    return exports;
}();
_;
